### PR TITLE
Validation of s3 objects deletion

### PR DESCRIPTION
**Pull request by pinzon**
This PR adds some tests to validate issue localstack/localstack#5558.

### CODE REVIEW

**Comment by whummer** [comment]
Hi @pinzon , can you please rebase the PR and resolve the conflicts, so we can get this merged? Thanks!

**Comment by whummer** [comment]
Hi @pinzon , sorry for the ping one more time ;) - the tests on `master` have now been fixed, can you please rebase the branch one more time, to get the builds green? Thx!

**Comment by pinzon** [comment]
@whummer of course, no problem!

**Review by whummer — APPROVED** [review]
LGTM! 👍

**Pull request merged**
